name = "AutoStructs"
uuid = "2e0df379-9877-4907-ab94-cd881f8d985b"
authors = ["Michael Abbott and Carlo Lucibello"]
version = "0.1.1"

[compat]
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
